package UI;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MenuUI extends javax.swing.JFrame {

    //Declaracion de variables
    private final JFileChooser selectorArchivo;
    private BufferedReader textBR;
    private BufferedReader pattBR;
    private boolean txtConf = false;
    private boolean pttConf = false;
    private boolean fb;
    private boolean bm;
    private boolean kmp;
    private boolean x = false;
    private String nombreTxt = "";
    private Main m = new Main();

    /**
     * Creates new form MenuUI
     */
    public MenuUI() {
        initComponents();
        selectorArchivo = new JFileChooser();
        selectorArchivo.setCurrentDirectory(new File("C:\\Desktop"));
        selectorArchivo.setFileFilter(new FileNameExtensionFilter("Archivos (*.txt, *.csv)", "txt", "csv"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        txtInicio = new javax.swing.JLabel();
        Algoritmos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AcercaDe = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AgregarDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panIn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panAD = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taPatron = new javax.swing.JTextArea();
        panA = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fbcb = new javax.swing.JCheckBox();
        kmpcb = new javax.swing.JCheckBox();
        bmcb = new javax.swing.JCheckBox();
        prosDatbtn = new javax.swing.JButton();
        panAcD = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        textArea2 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(12, 10, 62));

        Inicio.setBackground(new java.awt.Color(123, 30, 122));
        Inicio.setPreferredSize(new java.awt.Dimension(220, 40));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });

        txtInicio.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        txtInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInicio.setText("INICIO");

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(txtInicio)
                .addContainerGap())
        );

        Algoritmos.setBackground(new java.awt.Color(123, 30, 122));
        Algoritmos.setPreferredSize(new java.awt.Dimension(220, 40));
        Algoritmos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlgoritmosMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ALGORITMOS");

        javax.swing.GroupLayout AlgoritmosLayout = new javax.swing.GroupLayout(Algoritmos);
        Algoritmos.setLayout(AlgoritmosLayout);
        AlgoritmosLayout.setHorizontalGroup(
            AlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlgoritmosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AlgoritmosLayout.setVerticalGroup(
            AlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlgoritmosLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        AcercaDe.setBackground(new java.awt.Color(123, 30, 122));
        AcercaDe.setPreferredSize(new java.awt.Dimension(220, 40));
        AcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcercaDeMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ACERCA DE");

        javax.swing.GroupLayout AcercaDeLayout = new javax.swing.GroupLayout(AcercaDe);
        AcercaDe.setLayout(AcercaDeLayout);
        AcercaDeLayout.setHorizontalGroup(
            AcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcercaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AcercaDeLayout.setVerticalGroup(
            AcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcercaDeLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        AgregarDatos.setBackground(new java.awt.Color(123, 30, 122));
        AgregarDatos.setPreferredSize(new java.awt.Dimension(220, 40));
        AgregarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarDatosMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGREGAR DATOS");

        javax.swing.GroupLayout AgregarDatosLayout = new javax.swing.GroupLayout(AgregarDatos);
        AgregarDatos.setLayout(AgregarDatosLayout);
        AgregarDatosLayout.setHorizontalGroup(
            AgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        AgregarDatosLayout.setVerticalGroup(
            AgregarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarDatosLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(Algoritmos, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(AcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(AgregarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AgregarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Algoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(585, 500));

        panIn.setBackground(new java.awt.Color(34, 167, 240));
        panIn.setPreferredSize(new java.awt.Dimension(666, 500));

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel1.setText(" ");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("<html> <h1>Patter Matching<h1/>");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("<html> <h2>Programa para encontrar patrones en textos<h2/>");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panInLayout = new javax.swing.GroupLayout(panIn);
        panIn.setLayout(panInLayout);
        panInLayout.setHorizontalGroup(
            panInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel8)
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(186, 186, 186))
        );
        panInLayout.setVerticalGroup(
            panInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        panAD.setBackground(new java.awt.Color(167, 213, 237));
        panAD.setPreferredSize(new java.awt.Dimension(666, 500));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("<html> <h1>Cargar Texto: <h1/>");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("<html> <h1>Cargar Patrones: <h1/>");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Abrir archivo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Abrir archivo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("<html> <h2>Nota: Los formatos de archivos aceptados son .txt y .csv <h2/>");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        warning.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        taTexto.setColumns(20);
        taTexto.setRows(5);
        taTexto.setToolTipText("");
        taTexto.setBorder(javax.swing.BorderFactory.createTitledBorder("O  insertar aqui."));
        jScrollPane1.setViewportView(taTexto);

        taPatron.setColumns(20);
        taPatron.setRows(5);
        taPatron.setBorder(javax.swing.BorderFactory.createTitledBorder("O inserte aqui(Ej. nodo,a,ex,etc)"));
        jScrollPane2.setViewportView(taPatron);

        javax.swing.GroupLayout panADLayout = new javax.swing.GroupLayout(panAD);
        panAD.setLayout(panADLayout);
        panADLayout.setHorizontalGroup(
            panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panADLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panADLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panADLayout.createSequentialGroup()
                        .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panADLayout.createSequentialGroup()
                                .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                                .addGap(29, 29, 29)
                                .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panADLayout.setVerticalGroup(
            panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panADLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        panA.setBackground(new java.awt.Color(225, 166, 146));
        panA.setPreferredSize(new java.awt.Dimension(666, 500));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("<html> <h2>Algoritmos disponibles para la busqueda de patrones: <h2/>");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("<html> <h3>Nota: Debe cargar primero los archivos para poder utilizar los algoritmos!! <h3/>");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("<html> <h2>Fuerza Bruta <h2/>");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("<html> <h2>KMP<h2/>");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("<html> <h2>Boyer Moore<h2/>");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("<html> <h2>Ejecutar los algoritmos: <h2/>");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fbcb.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        fbcb.setText("Usar");
        fbcb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbcbMouseClicked(evt);
            }
        });
        fbcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbcbActionPerformed(evt);
            }
        });

        kmpcb.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        kmpcb.setText("Usar");
        kmpcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmpcbActionPerformed(evt);
            }
        });

        bmcb.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        bmcb.setText("Usar");

        prosDatbtn.setText("Procesar Datos");
        prosDatbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prosDatbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panALayout = new javax.swing.GroupLayout(panA);
        panA.setLayout(panALayout);
        panALayout.setHorizontalGroup(
            panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panALayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(panALayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panALayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kmpcb))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panALayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fbcb))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panALayout.createSequentialGroup()
                        .addGroup(panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prosDatbtn)
                            .addComponent(bmcb))))
                .addGap(56, 56, 56))
        );
        panALayout.setVerticalGroup(
            panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panALayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fbcb))
                .addGap(18, 18, 18)
                .addGroup(panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kmpcb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmcb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prosDatbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        panAcD.setBackground(new java.awt.Color(0, 102, 102));
        panAcD.setPreferredSize(new java.awt.Dimension(666, 500));

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("<html> <h1>Patter Matching<h1/>");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(255, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel5.setText(" ");

        textArea1.setBackground(new java.awt.Color(0, 102, 102));
        textArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textArea1.setEditable(false);
        textArea1.setText("Integrantes del proyecto:\n- Jhoaho Sanchez\n- Lisbeth Romo");

        textArea2.setBackground(new java.awt.Color(0, 102, 102));
        textArea2.setEditable(false);
        textArea2.setText("Manual de usuario:\n\nCodigo Fuente:");

        javax.swing.GroupLayout panAcDLayout = new javax.swing.GroupLayout(panAcD);
        panAcD.setLayout(panAcDLayout);
        panAcDLayout.setHorizontalGroup(
            panAcDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAcDLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(panAcDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel20)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(panAcDLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAcDLayout.setVerticalGroup(
            panAcDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAcDLayout.createSequentialGroup()
                .addGroup(panAcDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAcDLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAcDLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panAcD, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panAD, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panA, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panIn, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panAcD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(panAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 65, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(panA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 70, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(panIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Al hacer clic sobre incio, muestra el jpanel de inicio
    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked

        Inicio.setBackground(Color.decode("#F3C677"));
        AcercaDe.setBackground(Color.decode("#7B1E7A"));
        AgregarDatos.setBackground(Color.decode("#7B1E7A"));
        Algoritmos.setBackground(Color.decode("#7B1E7A"));
        panIn.setVisible(true);
        panA.setVisible(false);
        panAD.setVisible(false);
        panAcD.setVisible(false);

    }//GEN-LAST:event_InicioMouseClicked

    //Al hacer clic sobre algoritmos, muestra el jpanel de algoritmos
    private void AlgoritmosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlgoritmosMouseClicked

        Inicio.setBackground(Color.decode("#7B1E7A"));
        AcercaDe.setBackground(Color.decode("#7B1E7A"));
        AgregarDatos.setBackground(Color.decode("#7B1E7A"));
        Algoritmos.setBackground(Color.decode("#F3C677"));
        panIn.setVisible(false);
        panA.setVisible(true);
        panAD.setVisible(false);
        panAcD.setVisible(false);
    }//GEN-LAST:event_AlgoritmosMouseClicked

    //Al hacer clic sobre acerca de, muestra el jpanel de acerca de
    private void AcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcercaDeMouseClicked

        Inicio.setBackground(Color.decode("#7B1E7A"));
        AcercaDe.setBackground(Color.decode("#F3C677"));
        AgregarDatos.setBackground(Color.decode("#7B1E7A"));
        Algoritmos.setBackground(Color.decode("#7B1E7A"));
        panIn.setVisible(false);
        panA.setVisible(false);
        panAD.setVisible(false);
        panAcD.setVisible(true);
    }//GEN-LAST:event_AcercaDeMouseClicked

    //Al hacer clic sobre agregar datos, muestra el jpanel de agregar datos
    private void AgregarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarDatosMouseClicked

        Inicio.setBackground(Color.decode("#7B1E7A"));
        AcercaDe.setBackground(Color.decode("#7B1E7A"));
        AgregarDatos.setBackground(Color.decode("#F3C677"));
        Algoritmos.setBackground(Color.decode("#7B1E7A"));
        panIn.setVisible(false);
        panA.setVisible(false);
        panAD.setVisible(true);
        panAcD.setVisible(false);
    }//GEN-LAST:event_AgregarDatosMouseClicked

    //Metodo encargado de mostrar los paneles cuando se activa la ventana
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        if (x == false) {
            panA.setVisible(false);
            panAD.setVisible(false);
            panAcD.setVisible(false);
            panIn.setVisible(true);
            x = true;
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    //Metodo que ejecuta la accion de cargar los archivos de texto cuando se hace clic sobre el
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        int returnValue = selectorArchivo.showOpenDialog(this);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                File f = selectorArchivo.getSelectedFile();
                textBR = new BufferedReader(new FileReader(f));

                nombreTxt = f.getName();

                m.aniadirTexto(textBR, nombreTxt);
                warning.setText("El archivo se ha cargado con exito ");
                warning.setForeground(Color.BLACK);
                textBR.close();
                txtConf = true;
                panAD.setVisible(true);

            } catch (IOException e) {
                warning.setText("Atencion: No se ha podido cargar el archivo.");
                warning.setForeground(Color.red);

            }
        } else {

            warning.setText("Atencion: No se ha elegido un archivo!");
            warning.setForeground(Color.red);

        }
        panIn.setVisible(false);
        panAD.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    //Metodo que se encarga de cargar el archivo de patrones cuando se hace clic sobre un boton
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        int returnValue = selectorArchivo.showOpenDialog(this);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                File f = selectorArchivo.getSelectedFile();
                pattBR = new BufferedReader(new FileReader(f));

                nombreTxt = f.getName();

                m.aniadirPatron(pattBR, nombreTxt);
                warning.setText("El archivo se ha cargado con exito ");
                warning.setForeground(Color.BLACK);
                pattBR.close();
                pttConf = true;

            } catch (IOException e) {
                warning.setText("Atencion: No se ha podido cargar el archivo.");
                warning.setForeground(Color.red);

            }
        } else {

            warning.setText("Atencion: No se ha elegido un archivo!");
            warning.setForeground(Color.red);

        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void kmpcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmpcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmpcbActionPerformed

    private void fbcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbcbActionPerformed


    }//GEN-LAST:event_fbcbActionPerformed

    private void fbcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbcbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fbcbMouseClicked

    //Ejecuta la accion de procesar los datos cuando se hace clic sobre el boton
    private void prosDatbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prosDatbtnMouseClicked

        if ((pttConf == true && !taPatron.getText().isEmpty()) || (txtConf == true && !taTexto.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Opcion invalida, por favor escoja solo una opcion para cargar el texto y/o patron.", "Atencion", 2);
        } else {
            if (pttConf == true && txtConf == true) {
                callMethods();
            } else {

                if (pttConf == true && !taTexto.getText().isEmpty()) {
                    m.aniadirTextoFromTA(taTexto.getText());
                    callMethods();
                } else if (txtConf == true && !taPatron.getText().isEmpty()) {
                    m.aniadirPatronFromTA(taPatron.getText());
                    callMethods();
                } else if (!taTexto.getText().isEmpty() && !taPatron.getText().isEmpty()) {

                    m.aniadirPatronFromTA(taPatron.getText());
                    m.aniadirTextoFromTA(taTexto.getText());

                    callMethods();

                } else {
                    JOptionPane.showMessageDialog(null, "No se han cargado los archivos!!", "Atencion", 2);
                }

            }
        }
    }//GEN-LAST:event_prosDatbtnMouseClicked

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    }//GEN-LAST:event_formWindowDeactivated

    //Llama a los metodos de impresion de resultados dependiendo de los algoritmos seleccionados
    private void callMethods() {
        
        if ((fbcb.isSelected() == true && kmpcb.isSelected() == true) && (bmcb.isSelected() == true)) {
            m.imprimirResultados3O();
        } else {
            if (fbcb.isSelected() == false && kmpcb.isSelected() == true && bmcb.isSelected() == false) {
                m.imprimirResultadosKMP();
            } else if (fbcb.isSelected() == false && kmpcb.isSelected() == false && bmcb.isSelected() == true) {
                m.imprimirResultadosBM();
            } else if (fbcb.isSelected() == true && kmpcb.isSelected() == true && bmcb.isSelected() == false) {
                m.imprimirFBvsKMP();
            } else if (fbcb.isSelected() == true && kmpcb.isSelected() == false && bmcb.isSelected() == true) {
                m.imprimirFBvsBM();
            } else if (fbcb.isSelected() == false && kmpcb.isSelected() == true && bmcb.isSelected() == true) {
                m.imprimirKMPvsBM();
            } else if (fbcb.isSelected() == true && kmpcb.isSelected() == false && bmcb.isSelected() == false) {
                m.imprimirResultadosFB();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha selecionado algoritmo");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AcercaDe;
    private javax.swing.JPanel AgregarDatos;
    private javax.swing.JPanel Algoritmos;
    private javax.swing.JPanel Inicio;
    private javax.swing.JCheckBox bmcb;
    private javax.swing.JCheckBox fbcb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox kmpcb;
    private javax.swing.JPanel panA;
    private javax.swing.JPanel panAD;
    private javax.swing.JPanel panAcD;
    private javax.swing.JPanel panIn;
    private javax.swing.JButton prosDatbtn;
    private javax.swing.JTextArea taPatron;
    private javax.swing.JTextArea taTexto;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    private javax.swing.JLabel txtInicio;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
